"""base classes

Revision ID: 2cbc991667b6
Revises: b9a0cc6f9d09
Create Date: 2023-08-09 18:26:03.680521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cbc991667b6'
down_revision = 'b9a0cc6f9d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
