"""base classes

Revision ID: b9a0cc6f9d09
Revises: 
Create Date: 2023-08-09 17:53:06.235398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a0cc6f9d09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise', sa.String(), nullable=True),
    sa.Column('day', sa.String(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('name_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['name_id'], ['names.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preferences')
    op.drop_table('names')
    op.drop_table('Exercises')
    # ### end Alembic commands ###
